
owner: Satindar31 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website
    url: https://satindars-den.cf
  - name: Mercity
    url: https://site.mercitysmp.cf
  - name: Friends site cuz yes
    url: https://chill31.github.io

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.satindars-den.cf
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/73517520?s=1000&v=9
  name: Status
  introTitle: "Status page, duh"
  introMessage: Welcone
  navbar:
    - title: Website
      href: https://satindars-den.cf
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 1 * * *"
  uptime: "*/1 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
